package ventanas;

import javax.swing.JOptionPane;
import dataStructures.*;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import principal.ReaderMap;
import principal.SaveDB;

/**
 *
 * @author Diego
 */
public class InterfazPrincipal extends javax.swing.JFrame {

    public static String usuario = "";
    public static Map<String, String> dataBase;
    String contrasenia = "";
    public InterfazPrincipal() {
        initComponents();
        dataBase = new ReaderMap().mapa;
        this.setResizable(false);        
        this.setLocationRelativeTo(null);
        this.addWindowListener(new WindowAdapter() {
                @Override
                public void windowClosing(WindowEvent e) {
                    SaveDB usersSaver = new SaveDB(dataBase);
                    usersSaver.save();
                }
            });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonRegistrarse = new javax.swing.JButton();
        jButtonIniciarSesion = new javax.swing.JButton();
        jLabelUsuario = new javax.swing.JLabel();
        jLabelContrasenia = new javax.swing.JLabel();
        Usuario = new javax.swing.JTextField();
        Contrasenia = new javax.swing.JPasswordField();
        jLabelIcono = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabelFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButtonRegistrarse.setBackground(new java.awt.Color(0, 0, 0));
        jButtonRegistrarse.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jButtonRegistrarse.setForeground(new java.awt.Color(255, 255, 255));
        jButtonRegistrarse.setText("Registrarse");
        jButtonRegistrarse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRegistrarseActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonRegistrarse, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 330, 110, -1));

        jButtonIniciarSesion.setBackground(new java.awt.Color(0, 0, 0));
        jButtonIniciarSesion.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jButtonIniciarSesion.setForeground(new java.awt.Color(255, 255, 255));
        jButtonIniciarSesion.setText("Iniciar sesión");
        jButtonIniciarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonIniciarSesionActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonIniciarSesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 290, 150, -1));

        jLabelUsuario.setBackground(new java.awt.Color(0, 0, 0, 100)
        );
        jLabelUsuario.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabelUsuario.setForeground(new java.awt.Color(255, 255, 255));
        jLabelUsuario.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabelUsuario.setText("Usuario:");
        jLabelUsuario.setOpaque(true);
        getContentPane().add(jLabelUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 160, -1, 30));

        jLabelContrasenia.setBackground(new java.awt.Color(0, 0, 0, 100));
        jLabelContrasenia.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabelContrasenia.setForeground(new java.awt.Color(255, 255, 255));
        jLabelContrasenia.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabelContrasenia.setText("Contraseña:");
        jLabelContrasenia.setOpaque(true);
        getContentPane().add(jLabelContrasenia, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 210, -1, 30));

        Usuario.setBackground(new java.awt.Color(0, 0, 0, 150));
        Usuario.setForeground(new java.awt.Color(255, 255, 255));
        Usuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UsuarioActionPerformed(evt);
            }
        });
        getContentPane().add(Usuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 160, 170, 30));

        Contrasenia.setBackground(new java.awt.Color(0, 0, 0, 150));
        Contrasenia.setForeground(new java.awt.Color(255, 255, 255));
        Contrasenia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ContraseniaActionPerformed(evt);
            }
        });
        getContentPane().add(Contrasenia, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 210, 170, 30));

        jLabelIcono.setBackground(new java.awt.Color(0, 0, 0, 100));
        jLabelIcono.setFont(new java.awt.Font("Times New Roman", 3, 36)); // NOI18N
        jLabelIcono.setForeground(new java.awt.Color(255, 255, 255));
        jLabelIcono.setText("Stock UN");
        jLabelIcono.setOpaque(true);
        getContentPane().add(jLabelIcono, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 30, -1, 70));

        jComboBox1.setBackground(new java.awt.Color(0, 0, 0));
        jComboBox1.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jComboBox1.setForeground(new java.awt.Color(255, 255, 255));
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1.Stack", "2.Lista", "3.Lista referenciada", "4.Arbol" }));
        getContentPane().add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 190, 130, 30));

        jLabelFondo.setBackground(new java.awt.Color(255, 255, 255));
        jLabelFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/InicioNormal.jpg"))); // NOI18N
        jLabelFondo.setText("jLabel1");
        jLabelFondo.setAutoscrolls(true);
        getContentPane().add(jLabelFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 630, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonRegistrarseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRegistrarseActionPerformed
        //this.dispose();
        new RegistroPrueba(null, true, "Registro").setVisible(true);
    }//GEN-LAST:event_jButtonRegistrarseActionPerformed

    private void jButtonIniciarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonIniciarSesionActionPerformed
        usuario = Usuario.getText().trim(); 
        contrasenia = Contrasenia.getText().trim();
        if (usuario.equals("")|| contrasenia.equals("")) {
            JOptionPane.showMessageDialog(this, "Campo de usuario o contraseña vacios");
        }else{
            System.out.println("Accediendo: "+dataBase.get(usuario));
            String[] valor =  dataBase.get(usuario).split("\\*");
            if(dataBase.get(usuario)!=null && valor[0].equals(contrasenia)){
                SaveDB usersSaver = new SaveDB(dataBase);
                usersSaver.save();
                if(valor[1].equals("Administrador")){//Admin
                    dispose();
                    new GeneralPrueba();
                }else{
                    dispose();
                    new Clientes();
                }
            }else{
                if(dataBase.get(usuario)!=null) JOptionPane.showMessageDialog(null, "Contraseña incorrecta. Intente de nuevo");
                else JOptionPane.showMessageDialog(null, "Usuario o contraseña incorrectos. Intente de nuevo");
            }
        }
            
    }//GEN-LAST:event_jButtonIniciarSesionActionPerformed

    private void UsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_UsuarioActionPerformed

    private void ContraseniaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ContraseniaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ContraseniaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InterfazPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InterfazPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InterfazPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InterfazPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InterfazPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPasswordField Contrasenia;
    private javax.swing.JTextField Usuario;
    private javax.swing.JButton jButtonIniciarSesion;
    private javax.swing.JButton jButtonRegistrarse;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabelContrasenia;
    private javax.swing.JLabel jLabelFondo;
    private javax.swing.JLabel jLabelIcono;
    private javax.swing.JLabel jLabelUsuario;
    // End of variables declaration//GEN-END:variables
}
