package ventanas;

import principal.Producto;

/**
 *
 * @author Sammy Guergachi <sguergachi at gmail.com>
 */
public class VentanaProducto extends javax.swing.JDialog {

    public static boolean pulsado, cambioNombre;
    private Producto temp;
    private String nameBtn;

    public Producto getTemp() {
        return temp;
    }
    public void setTemp(Producto temp) {
        this.temp = temp;
    }
    
    public VentanaProducto(java.awt.Frame parent, boolean modal, String name) {
        super(parent, modal);
        pulsado = false;
        cambioNombre = false;
        nameBtn = name;
        initComponents();
        if(btn.getText().equals("Guardar Cambios")){
            nameText.setText(GeneralPrueba.getInformation()[0]);
            precioText.setText(GeneralPrueba.getInformation()[1]);
            stockText.setText(GeneralPrueba.getInformation()[2]);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        nameText = new javax.swing.JTextField();
        precioText = new javax.swing.JTextField();
        stockText = new javax.swing.JTextField();
        btn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        btn.setText(nameBtn);
        btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(142, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(stockText)
                    .addComponent(precioText)
                    .addComponent(nameText))
                .addGap(153, 153, 153))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addComponent(nameText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(precioText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addComponent(stockText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 46, Short.MAX_VALUE)
                .addComponent(btn)
                .addGap(34, 34, 34))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActionPerformed
        if(comprobarCampos()){
            pulsado = true;
            temp = new Producto(nameText.getText(), Long.parseLong(precioText.getText()), Integer.parseInt(stockText.getText()));
            System.out.println("Pulsado papá");
            dispose();
            if(!nameText.getText().equals(GeneralPrueba.getInformation()[0]))
                cambioNombre = true;
        }
    }//GEN-LAST:event_btnActionPerformed

    public boolean comprobarCampos(){
        return true;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn;
    private javax.swing.JTextField nameText;
    private javax.swing.JTextField precioText;
    private javax.swing.JTextField stockText;
    // End of variables declaration//GEN-END:variables
}
